DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS forum CASCADE;
DROP TABLE IF EXISTS thread CASCADE;
DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS vote CASCADE;

CREATE EXTENSION IF NOT EXISTS CITEXT;

CREATE TABLE IF NOT EXISTS "user" (
  id SERIAL NOT NULL PRIMARY KEY,
  about TEXT,
  email CITEXT NOT NULL UNIQUE,
  fullname TEXT,
  nickname CITEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS forum (
  id SERIAL NOT NULL PRIMARY KEY,
  posts INTEGER DEFAULT 0,
  slug CITEXT,
  threads INTEGER DEFAULT 0,
  title TEXT NOT NULL,
  user_id INTEGER REFERENCES "user"(id) NOT NULL
);

CREATE TABLE IF NOT EXISTS thread (
  id SERIAL NOT NULL PRIMARY KEY,
  user_id INTEGER REFERENCES "user"(id) NOT NULL,
  created TIMESTAMP,
  forum_id INTEGER REFERENCES forum(id) NOT NULL,
  message TEXT,
  slug CITEXT UNIQUE,
  title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS post (
  id SERIAL NOT NULL PRIMARY KEY,
  user_id INTEGER REFERENCES "user"(id) NOT NULL,
  created TIMESTAMP,
  forum_id INTEGER REFERENCES forum(id) NOT NULL,
  is_edited BOOLEAN DEFAULT FALSE,
  message TEXT,
  parent_id INTEGER,
  thread_id INTEGER REFERENCES thread(id) NOT NULL
);

CREATE TABLE IF NOT EXISTS vote (
  id SERIAL NOT NULL PRIMARY KEY,
  user_id INTEGER REFERENCES "user"(id) UNIQUE NOT NULL,
  voice SMALLINT,
  thread_id INT REFERENCES thread(id) UNIQUE NOT NULL
);
